[package]
name = "token_cognito"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
aws-config = "0.55.2"
aws-sdk-cognitoidentityprovider = "0.27.0"
cognito_srp = "0.1.2"
